// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Mpkpjq8uOBzfLBR9IdJS0USCJ90Jj1E',
    appId: '1:456727832172:web:02f2e066b47f1d68b85a49',
    messagingSenderId: '456727832172',
    projectId: 'f1-api-info',
    authDomain: 'f1-api-info.firebaseapp.com',
    storageBucket: 'f1-api-info.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy9Go5AcZsrLNH1fZFXCFjxFbviF0RSHA',
    appId: '1:456727832172:android:77ed12a23c6f3ef8b85a49',
    messagingSenderId: '456727832172',
    projectId: 'f1-api-info',
    storageBucket: 'f1-api-info.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9S3MXJpCzPTVM_66mnsHiWeM6kstJZFY',
    appId: '1:456727832172:ios:1f3b964b9fd36b48b85a49',
    messagingSenderId: '456727832172',
    projectId: 'f1-api-info',
    storageBucket: 'f1-api-info.appspot.com',
    iosBundleId: 'es.ivanzambrananaranjo.f1info',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9S3MXJpCzPTVM_66mnsHiWeM6kstJZFY',
    appId: '1:456727832172:ios:1f3b964b9fd36b48b85a49',
    messagingSenderId: '456727832172',
    projectId: 'f1-api-info',
    storageBucket: 'f1-api-info.appspot.com',
    iosBundleId: 'es.ivanzambrananaranjo.f1info',
  );
}
